version: '2'
services:
  ifm_simple_1-app:
    image: ifm_simple_1
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ifm_simple_1-postgresql:5432/ifm_simple_1
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  ifm_simple_1-postgresql:
    extends:
      file: postgresql.yml
      service: ifm_simple_1-postgresql
