version: '2'
services:
  ifm_simple_1-postgresql:
    image: postgres:12.3
    # volumes:
    #     - ~/volumes/jhipster/ifm_simple_1/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=ifm_simple_1
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
